<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Clustering.Dendrograms</RootNamespace>
    <AssemblyName>Clustering.Dendrograms</AssemblyName>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\..\src\clustering\dendrogram\**\*.cs" Link="dendrogram\%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Graphs.Primitives\Graphs.Primitives.csproj" />
    <ProjectReference Include="..\Clustering.Primitives\Clustering.Primitives.csproj" />
  </ItemGroup>
</Project>
