<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Maths.Geometry</RootNamespace>
    <AssemblyName>Maths.Geometry</AssemblyName>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\..\src\maths\geometry\**\*.cs" Link="geometry\%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Maths.LinAlg\Maths.LinAlg.csproj" />
    <ProjectReference Include="..\Maths.Distance\Maths.Distance.csproj" />
    <ProjectReference Include="..\Maths.Distributions\Maths.Distributions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Numerics.Tensors" Version="10.0.0" />
  </ItemGroup>
</Project>
