<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>TDA.Ph</RootNamespace>
    <AssemblyName>TDA.Ph</AssemblyName>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\..\src\tda\ph\**\*.cs" Link="ph\%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Graphs.Primitives\Graphs.Primitives.csproj" />
    <ProjectReference Include="..\Graphs.Spectral\Graphs.Spectral.csproj" />
    <ProjectReference Include="..\Maths.LinAlg\Maths.LinAlg.csproj" />
    <ProjectReference Include="..\Maths.Topology\Maths.Topology.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="TDA.Ph.Tests" />
  </ItemGroup>
</Project>
