<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Clustering.Statistical.GMM</RootNamespace>
    <AssemblyName>Clustering.Statistical.GMM</AssemblyName>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="../../src/clustering/statistical/gmm/**/*.cs" Link="gmm/%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Maths.LinAlg/Maths.LinAlg.csproj" />
    <ProjectReference Include="../Maths.Geometry/Maths.Geometry.csproj" />
    <ProjectReference Include="../Maths.Distance/Maths.Distance.csproj" />
    <ProjectReference Include="../Clustering.Dendrograms/Clustering.Dendrograms.csproj" />
  </ItemGroup>
</Project>
