<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Graphs.Models.Potts</RootNamespace>
    <AssemblyName>Graphs.Models.Potts</AssemblyName>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\..\src\graphs\models\potts\**\*.cs" Link="potts\%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>
</Project>
