<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Graphs.Spectral</RootNamespace>
    <AssemblyName>Graphs.Spectral</AssemblyName>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\..\src\graphs\spectral\*.cs" Link="spectral\%(Filename)%(Extension)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Graphs.Primitives\Graphs.Primitives.csproj" />
    <ProjectReference Include="..\Maths.LinAlg\Maths.LinAlg.csproj" />
  </ItemGroup>
</Project>
